/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package accesscontrolmanagementsystem;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import project.*;
import java.sql.*;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 * View visitor list on current date ACMS
 * @author GueyLing
 */
public class SecurityGuardHome extends javax.swing.JFrame {

    public int user_id;

    /**
     * Creates new form SecurityGuardHome
     */
    public SecurityGuardHome() {
        initComponents();
        Date date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        String now = formatter.format(date);
        jLabel5.setText(String.valueOf(now));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });


        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("ACME COMPANY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jPanel3.setBackground(new java.awt.Color(170, 215, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Visitor List");
        jPanel3.add(jLabel2);


        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 290, 50));

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });


        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Visitor Log");

        jPanel4.add(jLabel3);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 290, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Visitor Access Record");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel6.setText("Date:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Visitor Name", "Phone No.", "IC", "Ticket ID", "Booked Time", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 850, 310));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)

        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Direct users to view the visitor log
     * @param evt 
     */
    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        setVisible(false);

        SecurityGuardVisitorLog jf = new SecurityGuardVisitorLog();

        jf.setVisible(true);
        jf.setExtendedState(JFrame.MAXIMIZED_BOTH);
        jf.user_id = user_id;
    }//GEN-LAST:event_jPanel4MouseClicked


    /**
     * Display all visitors on current date
     * @param evt 
     */
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // get current date
        Date date = new Date();
        Date currentTime = null, appointmentTime, checkoutTime;
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        String now = formatter.format(date);
        // get current time
        SimpleDateFormat timeFormatter = new SimpleDateFormat("hh:mma");
        String time = timeFormatter.format(date).toLowerCase();
        try {
            currentTime = timeFormatter.parse(time);
        } catch (ParseException ex) {
            Logger.getLogger(SecurityGuardHome.class.getName()).log(Level.SEVERE, null, ex);
        }

        ResultSet rs = Select.getData("select * from users JOIN visit_ticket ON users.id = visit_ticket.user_id JOIN visit_status ON visit_ticket.id = visit_status.ticket_id WHERE visit_ticket.date = '" + now + "' ");

        try {
            while (rs.next()) {
              
                String setTime = rs.getString(10);
                String endTime = rs.getString(11);
                appointmentTime = timeFormatter.parse(setTime);
                checkoutTime = timeFormatter.parse(endTime);
                // calculate difference (in minutes) between current time and scheduled time
                long differenceInMilliSeconds = currentTime.getTime() - appointmentTime.getTime();
                long differenceInMilliSeconds2 = checkoutTime.getTime() - currentTime.getTime();
                long differenceInHours = (differenceInMilliSeconds / (60 * 60 * 1000)) % 24;
                long differenceInMinutes = (differenceInMilliSeconds / (60 * 1000)) % 60;
                long differenceInHours2 = (differenceInMilliSeconds2 / (60 * 60 * 1000)) % 24;
                long differenceInMinutes2 = (differenceInMilliSeconds2 / (60 * 1000)) % 60;
                int id = rs.getInt(14);
                // if late than 30 mintues from appointed time, change status to did not turn up
                if (differenceInHours > 0 || differenceInMinutes > 30) {
                    if (rs.getString(20).equals("not yet arrive")) {
                        String Query;
                        Query = "update visit_status set status = 'did not turn up' where ticket_id = " + id + " ";
                        InsertUpdateDelete.setDataWithoutJOption(Query);
                    }
                }
                // if did not check out after appointed time, check out automatically
                if (differenceInHours2 < 0 || differenceInMinutes2 < 0) {
                    if (rs.getString(20).equals("checked in")) {
                        String Query;
                        Query = "update visit_status set status = 'checked out', exit_time = '"+time+"', exit_time_guard_id = 17 where ticket_id = " + id + " ";
                        InsertUpdateDelete.setDataWithoutJOption(Query);
                    }
                }

            }
            rs.close();
        } catch (SQLException | ParseException e) {
            JOptionPane.showMessageDialog(null, e);
        }

        // display data
        ResultSet rs1 = Select.getData("select * from users JOIN visit_ticket ON users.id = visit_ticket.user_id JOIN visit_status ON visit_ticket.id = visit_status.ticket_id WHERE visit_ticket.date = '" + now + "' and visit_ticket.status = 'approved'");
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        try {
            while (rs1.next()) {
                model.addRow(new Object[]{rs1.getString(7), rs1.getString(1), rs1.getString(4), rs1.getString(6), rs1.getString(14), rs1.getString(10) + " - " + rs1.getString(11), rs1.getString(20)});
            }
            rs1.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_formComponentShown

    /**
     * Allow security guard to check in or check out
     * @param evt 
     */
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String value1 = model.getValueAt(index, 6).toString(); //status
        int value2 = Integer.parseInt(model.getValueAt(index, 0).toString());
        int ticket_id = Integer.parseInt(model.getValueAt(index, 4).toString());

        if (value1.equals("not yet arrive") || value1.equals("checked in")) {
            ResultSet rs = Select.getData("select * from users JOIN visit_ticket ON users.id = visit_ticket.user_id where users.id='" + value2 + "' AND visit_ticket.id= '" + ticket_id + "' ");
            try {
                if (rs.next()) {
                    String name = rs.getString(1);
                    String imageUrl = rs.getString(8);
                    setVisible(false);

                    SecurityGuardVerifyVisitor jf = new SecurityGuardVerifyVisitor();
                    jf.setVisible(true);
                    jf.visitor_name(name);
                    jf.set_button_text(value1);
                    jf.set_image(imageUrl);
                    jf.ticket_id = ticket_id;
                    jf.user_id = user_id;

                }
            } catch (IOException | SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecurityGuardHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecurityGuardHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecurityGuardHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecurityGuardHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            JFrame jf = new SecurityGuardHome();
            jf.setVisible(true);
            jf.setExtendedState(JFrame.MAXIMIZED_BOTH);
        });
       
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;

    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;

    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
