/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package accesscontrolmanagementsystem;


import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import project.InsertUpdateDelete;
import java.time.LocalDate;  
import java.time.ZoneId;
import java.util.Date;

/**
 * Visitor Home Page (Allows them to submit application for visit pass) ACMS
 * @author GueyLing
 */
public class VisitorHome extends javax.swing.JFrame {

    public int user_id;
    public boolean successState = false;

    /**
     * Creates new form VisitorHome
     */
    public VisitorHome() {
        initComponents();
         //int user_id =
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ticketHistoryPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        timePicker3 = new com.github.lgooddatepicker.components.TimePicker();
        timePicker4 = new com.github.lgooddatepicker.components.TimePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("ACME COMPANY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jPanel3.setBackground(new java.awt.Color(170, 215, 255));

        jLabel2.setText("Apply Visit Pass");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel3.add(jLabel2);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 290, 50));

        ticketHistoryPanel.setBackground(new java.awt.Color(153, 204, 255));
        ticketHistoryPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticketHistoryPanelMouseClicked(evt);
            }
        });

        jLabel3.setText("Ticket History");
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ticketHistoryPanel.add(jLabel3);

        jPanel1.add(ticketHistoryPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 290, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Apply Visit Pass");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 590, -1));

        jLabel6.setText("Image URL (Please upload the latest picture of yourself for authentication purpose):");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel7.setText("From");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        jLabel8.setText("To");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, -1, -1));

        jLabel9.setText("Date:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        jLabel10.setText("Reason:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel2.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, -1, -1));

        jLabel11.setText("* DISCLAIMER:  Your access will be denied if you are more than 30 minutes late.");
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        LocalDate localDate = LocalDate.now();
        LocalDate visitDate = localDate.plusDays(7);
        Date date = Date.from(visitDate.atStartOfDay(ZoneId.systemDefault()).toInstant());
        jDateChooser1.getJCalendar().setMinSelectableDate(date);
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 590, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 610, 100));
        jPanel2.add(timePicker3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 210, -1));
        jPanel2.add(timePicker4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 210, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 1020, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Submit the application for the security officer to review
     * @param evt 
     */
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String imageUrl = jTextField1.getText();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String date, bookFrom, bookTo;
        try{
        date = df.format(jDateChooser1.getDate());
        bookFrom = timePicker3.getText();
        bookTo = timePicker4.getText();
        }catch(Exception e){
            date = "";
            bookFrom = "";
            bookTo = "";
        }
        String reason = jTextArea1.getText();
        String status = "pending";
        
        // Make sure the users enter all the fields
        if(imageUrl.equals("")||date.equals("")||bookFrom.equals("")||bookTo.equals("")||reason.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter all the fields.");
        }else{
            String Query;
            Query = "insert into visit_ticket values('"+imageUrl+"','"+date+"','"+bookFrom+"','"+bookTo+"','"+reason+"','"+status+"','0' ,'"+user_id+"','',NULL,'')";
            InsertUpdateDelete.setData(Query, "Submitted Successfully");
            successState = true;
            setVisible(false);
            VisitorTicketHistory jf= new VisitorTicketHistory();
            jf.setVisible(true);
            jf.setExtendedState(JFrame.MAXIMIZED_BOTH);  
            jf.user_id = user_id;
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * Direct users to view their application tickets and status
     * @param evt 
     */
    private void ticketHistoryPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticketHistoryPanelMouseClicked
      setVisible(false);
      VisitorTicketHistory jf= new VisitorTicketHistory();
      jf.setVisible(true);
      jf.setExtendedState(JFrame.MAXIMIZED_BOTH);  
      jf.user_id = user_id;
    }//GEN-LAST:event_ticketHistoryPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisitorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisitorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisitorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisitorHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            JFrame jf= new VisitorHome();
            jf.setVisible(true);
            jf.setExtendedState(JFrame.MAXIMIZED_BOTH);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JButton submitButton;
    private javax.swing.JPanel ticketHistoryPanel;
    public com.github.lgooddatepicker.components.TimePicker timePicker3;
    public com.github.lgooddatepicker.components.TimePicker timePicker4;
    // End of variables declaration//GEN-END:variables
}
